#' This function imports the binary table output from RawGeno
#' 
#'
#' This function converts the binary table generated by an active session of RawGeno
#' to a format that can be read by other functions in this package
#' 
#' @param \code{outfilename}  desired filename for peak height files
#' @keywords STRUCTURE, AFLP, RawGeno
#' @export
#' @examples
#' RawGeno_import(outfile.txt) 


RawGeno_import <- function(outfilename)
{
  dat <- data.binary$data.height.raw
  tdat <- t(dat)
  names <- vector(length = ncol(tdat))
  names[1] <-""
  for (i in 2:ncol(tdat))
  {
    names[i] <- paste("Loc_",i,sep="")
  }
  colnames(tdat) <- names
  tdat[which(tdat==0)] = NA
  write.table(tdat, outfilename, na="", quote=FALSE, sep="\t")
}
