#' Write a standard fomatted STRUCTURE dataset
#'
#' This function reads a \code{STRUCTURE}-formatted AFLP dataset and returns a row labelled dataframe
#' @param \code{dat}  a dataframe containing AFLP data generated by read.structure
#' @param \code{outfile}  desired filename for filtered Structure dataset 
#'
#' @keywords STRUCTURE, AFLP, write
#' @export
#' @examples
#' write.structure(dat, myOutfile)


write.structure <- function(dat,outfile){
  write(rep(0,(ncol(dat)-1)),file=outfile, sep="\t", ncolumns=ncol(dat)-1)
  write.table(dat,outfile, quote=F, sep="\t", col.names=F, append=T)
  cat("Final dataset written, dimensions:\n")
  cat(nrow(dat),"individuals\n")
  cat((ncol(dat)-1),"loci\n")
}
