#' Write a standard fomatted STRUCTURE dataset
#'
<<<<<<< HEAD
#' This function reads a \code{STRUCTURE}-formatted AFLP dataset and returns a row labelled dataframe
=======
#' This function reads an \code{STRUCTURE} formatted AFLP dataset and returns a row labelled dataframe
>>>>>>> ee23773d54dca35e89bb729790c869295ae2f907
#' @param \code{dat}  a dataframe containing AFLP data generated by read.structure
#' @param \code{outfile}  desired filename for filtered Structure dataset 
#'
#' @keywords STRUCTURE, AFLP, write
#' @export
#' @examples
#' write.structure(dat, myOutfile)


write.structure <- function(dat,outfile){
<<<<<<< HEAD
  write(rep(0,(ncol(dat)-1)),file=outfile, sep="\t", ncolumns=ncol(dat)-1)
  write.table(dat,outfile, quote=F, sep="\t", col.names=F, append=T)
  cat("Final dataset written, dimensions:\n")
  cat(nrow(dat),"individuals\n")
  cat((ncol(dat)-1),"loci\n")
=======
  write(rep(0,(ncol(filtered_dat)-1)),file=outfile, sep="\t", ncolumns=ncol(filtered_dat)-1)
  write.table(filtered_dat,outfile, quote=F, sep="\t", col.names=F, append=T)
  cat("Final dataset written, dimensions:\n")
  cat(nrow(filtered_dat),"individuals\n")
  cat((ncol(filtered_dat)-1),"loci\n")
>>>>>>> ee23773d54dca35e89bb729790c869295ae2f907
}
